### ISSUE TITLE
Is there a way to run SFP under linux?

### ISSUE THREAD

**Issue by Midou36O** [PhantomGamers/SFP#10]
There doesn't seem to be any alternatives to SFP for linux, so i'm wondering if there is a way to actually make SFP work under linux?

**Comment by PhantomGamers** [comment]
Yeah, simply download the Linux version of SFP. There are binaries provided for Windows, Linux, and Mac OSX. Note that as the README states, friends patching is currently unsupported on Linux and OSX as they use a different file format from Windows.

SFP is open source and the initial implementation of friends patching is available here https://github.com/PhantomGamers/SFP/tree/main/SFP/Models/ChromeCache/Simple However, as I don't run Linux myself and I work on this free of charge it is unlikely that I will get that part working myself. PRs are welcome :)
