### ISSUE TITLE
New steam update removing skins

### ISSUE THREAD

**Issue by ivelieu** [PhantomGamers/SFP#123]
[https://steamcommunity.com/games/593110/announcements/detail/3687931965598323437](https://steamcommunity.com/games/593110/announcements/detail/3687931965598323437)
Steam Client Update - June 14th
[https://steamcommunity.com/app/593110/eventcomments/5514142341086067567](https://steamcommunity.com/app/593110/eventcomments/5514142341086067567)
And the update comment thread (as usual, a  mixed bag of praise and harsh criticism) 

It seems like steam completely dropped support for skins, and had the gall to not even mention this in their so-called patch notes. 
Does this mean the end for SFP? I hope Valve reverts some of this to give us skins back at least, but considering their track record I'm very doubtful.
It's a shame, too, I only set up SFP a week ago for a custom skin.

**Comment by PhantomGamers** [comment]
SFP still works. Skin authors are working on skins for the new client.

https://github.com/AikoMidori/SteamSkins has a few options
