### ISSUE TITLE
As of the newest steam update, this happens.

### ISSUE THREAD

**Issue by refriedfood** [PhantomGamers/SFP#152]
I tried to go back to steam's 2022 version, which I love, and it still gives the same error. Also, the css doesn't work--which was basically the entire reason I use this.

```
* {
   font-family: Arial !important;
}

```

When clicking on the friendname drop down arrow, it produces the following:
![](https://ptpimg.me/1cf0c5.png)

**Comment by PhantomGamers** [comment]
> Also, the css doesn't work--which was basically the entire reason I use this.

Where are you putting that css?

Also for the error, does the error not come up if you restart Steam without SFP running? Do you have js injection enabled in SFP's settings?

**Comment by refriedfood** [comment]
> Where are you putting that css?
> Also for the error, does the error not come up if you restart Steam without SFP running? Do you have js injection enabled in SFP's settings?

Steam\clientui\friends.custom.css
Steam\clientuiofriends.custom.css

The error comes with or without it running, and only if I'm logged in without the -no-browser -noreactlogin switch (i.e. normal mode) and regardless if I inject it and close or inject and keep it open.

**Comment by PhantomGamers** [comment]
css goes in steamui by default, so that is why it is not working. use the `open file` button on SFP to access the correct path for your css files

if you are getting that Steam error even without SFP running I'm not really sure what to suggest. Perhaps try shutting down Steam and deleting the following folders:
`Steam\steamui`
`Steam\clientui`
`%localappdata%\Steam\htmlcache\Cache`
and then start Steam again

**Comment by refriedfood** [comment]
This doesn't make any sense. Putting those two css files in that directory is what always worked before. Has it changed? Also, if I delete those directories, I might as well reinstall steam, because it will update--which I do not want it to do.

I deliberately use the 2022 version of steam, because I don't care for the browser. Does that mean I'm shit out of luck now?

**Comment by PhantomGamers** [comment]
I dont know but I will only be supporting the latest version of Steam.

**Comment by refriedfood** [comment]
That's dumb and lazy.

**Comment by PhantomGamers** [comment]
If you're so smart and motivated, feel free to contribute.

Put up or shut up
