### ISSUE TITLE
Port 8080

### ISSUE THREAD

**Issue by Fan4eGGG** [PhantomGamers/SFP#161]
Good afternoon.
i apologize for my ignorance but i would like to ask you something.
the thing is that when i install SFP i get an error: 
`[Error] Could not fetch browser, SFP either tried to inject too early or another service is running on port 8080`
just the thing is that this port is used by a server on [Docker](https://github.com/docker) that i installed.
i would like to know if there is a possibility... i dont know how to explain. to move the SFP "server", or something like that, to not use port 8080?
thank you.

**Comment by PhantomGamers** [comment]
SFP doesn't use port 8080, Steam does. SFP injects into Steam by communicating with its CEF debugging server, which runs on port 8080. As far as I am aware there is no way to change this port, outside of memory manipulation, so the best advice would be to simply change the port of whichever service you have running on 8080.
