### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by mixm1xmix** [PhantomGamers/SFP#198]
Steam seems to be disregarding this tool as of the last few weeks. Updated to the latest release, no change. Anybody else experiencing this?

**Comment by PhantomGamers** [comment]
They changed css class names in the Steam beta so skins will need to be updated to work with the new class names. For now, opt out of the Steam beta.

**Comment by mixm1xmix** [comment]
Thanks, I had forgotten I even opted into that. Cheers!
