### ISSUE TITLE
lubrary not patching for anything than OG Steam

### ISSUE THREAD

**Issue by CoastalZ** [PhantomGamers/SFP#2]
i resetted the steam selected the metro for steam skin patched and theres still default libraryu]==
or im just dumb and i dont understand how to use it

**Comment by PhantomGamers** [comment]
The Metro For Steam skin is for the main client only. The library and friends list use a different system which doesn't natively support skinning. This tool simply enables the use of skins.

I would recommend following this great guide which includes mention of the multiple friends list skins that are available from the community. https://steamcommunity.com/sharedfiles/filedetails/?id=1941650801

**Comment by CoastalZ** [comment]
aight thx!
