### ISSUE TITLE
The config file may not be writable relative to the binary

### ISSUE THREAD

**Issue by ShayBox** [PhantomGamers/SFP#203]
I packaged `SFP_UI` as an [AUR](https://aur.archlinux.org/packages/sfp-ui-bin) package, but because it's packaged in a system directory (`/usr/bin/SFP_UI`), the config file [`SFP.config`](https://github.com/PhantomGamers/SFP/blob/main/SFP_UI/Program.cs#L117) is not writable and settings do not save.

The config file appears to be JSON and should have the `.json` file extension, and be placed within the standard locations depending on the platform if the relative path is not writable.

This issue can affect Windows if the program gets packaged using a third-party installer, or package manager.  
(Winget, Scoop, Chocolatey, etc.)

Windows: `%AppData%`
Linux: `$XDG_CONFIG_HOME` with a fallback of `$HOME/.config` when not set
macOS: `~/Library/Preferences`

**Comment by PhantomGamers** [comment]
This is something I plan on changing in the next update. Currently I'm waiting for the next update of both avalonia and fluentavalonia to drop and then I'm going to upgrade to net8 and redo the configuration system, and when I do that I will take this into account.

**Comment by PhantomGamers** [comment]
@GrahSebastian having to launch it from the terminal must be some specific problem with the aur package, I'm not too familiar with that. But with the version released on github, you can just double click on the executable to run it from your DE, no terminal necessary.

**Comment by ShayBox** [comment]
Yes, the AUR package does not include a desktop entry or icon, I'm still waiting for the programs config file to be moved, so the settings save, until then you either have to touch/chmod the location for the config or manually download and run the binary in a location that is writable.
