### ISSUE TITLE
themes not loading anymore in client

### ISSUE THREAD

**Issue by Fan4eGGG** [PhantomGamers/SFP#204]
Hello. I wanted to ask, days 3-5 ago stopped loading topics in the client itself. although other elements such as the list of friends, messages, etc. are loaded quietly, as shown in [this screenshot](https://imgur.com/a/ruymK1g). this applies to any topic loaded through SFP.
what could be the problem and how to fix it?
thank you.

**Comment by elirasza** [comment]
I have the same problem. The only working UI element on my side is the loading popup when you start / stop Steam.

**Comment by Fan4eGGG** [comment]
> so skins need to be updated

tnx! thats worked!
