### ISSUE TITLE
SFP Patching Friends List But Not Main Client

### ISSUE THREAD

**Issue by BitingHalberd** [PhantomGamers/SFP#205]
Ever since about a week ago SFP has not been properly patching the main client with skins. It seems to apply to the friends list without issue but the main client remains the default appearance. I have tried more than one skin and they all seem to behave like this. Not sure if this is known, an issue with a steam update, or something I'm doing wrong.

**Comment by PhantomGamers** [comment]
See https://github.com/PhantomGamers/SFP/issues/204#issuecomment-2104197951
