### ISSUE TITLE
SFP bricked my steam

### ISSUE THREAD

**Issue by ghost** [PhantomGamers/SFP#207]
I attempted to launch SFP on windows 8.1 but the ui would not launch. Then my steam ui wouldn't launch, it would come up with an error message saying "steamwebhelper is not responding". then it would never open again. Steam appears to be running in task manager but it isn't doing anything. Ive already tried reinstalling steam but it has not worked. I might have to reinstall my OS.

**Comment by PhantomGamers** [comment]
lol, just delete sfp. sfp only affects steam while its running. and windows 8.1 is not supported by sfp, you must be running windows 10 or higher.
