### ISSUE TITLE
[Feature request]Port Settings

### ISSUE THREAD

**Issue by a549956952** [PhantomGamers/SFP#211]
I stumbled upon a comment on https://gist.github.com/davispuh/6600880?permalink_comment_id=4702206#gistcomment-4702206 that steam can use -devtools-port to specify the debug port.

I compiled a modified SFP to make sure this would work.
Only the following modifications were made.
`CefDebuggingUrl = ‘http://127.0.0.1:8081’`
Add `-devtools-port 8081` to the startup parameters
![Snipaste_2024-12-14_02-38-39](https://github.com/user-attachments/assets/abeaeb5b-c889-4eb3-882e-613a754b6a7f)
![Snipaste_2024-12-14_02-38-21](https://github.com/user-attachments/assets/af9e8a1a-4c45-4d86-8ae3-c1da732c5523)

This avoids conflicts with programmes on port 8080.

**Comment by PhantomGamers** [comment]
I made a prerelease with this feature here https://github.com/PhantomGamers/SFP/releases/tag/0.0.60-beta1
