### ISSUE TITLE
SFP tries to inject before it has launched Steam

### ISSUE THREAD

**Issue by ZachFett** [PhantomGamers/SFP#212]
This started happening about two weeks ago, I was using SFP for a good 4~ months without any issues, now I have to always manually start injection. I've watched as the log will say it tried to inject a good 10-20 seconds before the Steam process opens. I have all of the checkboxes ticked regarding starting SFP and Steam on start, as well as inject on start. Is there a way to adjust the delay? If it would just give Steam another few seconds to load it'd be fine.
![image](https://github.com/user-attachments/assets/836e3cd1-2e6c-42ff-a362-55525e382ea5)

**Comment by PhantomGamers** [comment]
I made a prerelease with a setting to delay injection here https://github.com/PhantomGamers/SFP/releases/tag/0.0.60-beta1

**Comment by ZachFett** [comment]
> I made a prerelease with a setting to delay injection here https://github.com/PhantomGamers/SFP/releases/tag/0.0.60-beta1

Perfect, thank you so much!
