### ISSUE TITLE
suggestion: add an option to increase font size

### ISSUE THREAD

**Issue by Mantha065** [PhantomGamers/SFP#22]
This may not fall under the scope of this project, but for the life of me I can't find any way (that works) to increase the font size of Steam. Stuff like the "ABOUT THIS GAME" sections on the store page, or the descriptions for Workshop addons, all of that text is getting too small for my eyes to read, but Steam has no way to increase the font size. I'd love if SFP had an extra option to adjust the sizes of text like that.

**Comment by PhantomGamers** [comment]
That's something that you'd have to change in the webkit skin you're using, like https://github.com/AikoMidori/steam-dark-mode or https://github.com/BallOpener/steam-dark-mode/tree/beta2

SFP currently only facilitates the skinning of the library and friends list, but doesn't actually offer any skinning options of its own.
