### ISSUE TITLE
After today's Steam update, SFP fails to hide What's New

### ISSUE THREAD

**Issue by Mantha065** [PhantomGamers/SFP#29]
Just letting you  know that the new Steam update seems to have stumped SFP's previous ability to move What's New to the very bottom of the Library.

**Comment by PhantomGamers** [comment]
SFP is just a tool that allows the library and friends list to be skinned, but it does not provide any skinning options on its own.

This is something that the skin author would have to fix. Probably https://github.com/AikoMidori/steam-library but whether it's that one or a different one this issue should be reported to the author of the skin you are using.
