### ISSUE TITLE
SFP crashes on exit

### ISSUE THREAD

**Issue by SleepDaemon** [PhantomGamers/SFP#3]
As the title says it gives a pop up saying it crashes with some error code. But after clicking continue windows resumes restarting.

**Comment by SleepDaemon** [comment]
Also a repose to your comment in the other issue sorry should've made a separate one.

You did say don't mention known issues but the only issue I saw was the one I made.

**Comment by PhantomGamers** [comment]
This is a known issue as mentioned in the readme.

**Comment by PhantomGamers** [comment]
Fixed in 0.0.7
