### ISSUE TITLE
Crash if files are already patched.

### ISSUE THREAD

**Issue by GentlePuppet** [PhantomGamers/SFP#35]
If the files are already patched then when it tries to patch them again it crashes entirely. 

If you set it to patch on app launch this also causes it to instantly crash if the files are already patched.

[SFP.log](https://github.com/PhantomGamers/SFP/files/9387766/SFP.log)

**Comment by PhantomGamers** [comment]
this is the problem:

> 2022-08-20 13:25:46.7036|ERROR|SFP.Models.Log|System.UnauthorizedAccessException: Access to the path 'c:\gaming programs\steam\steamui\css\library.css.old' is denied.

This file should not be in the `steamui\css` folder

**Comment by GentlePuppet** [comment]
I see, I don't remember putting that there, but maybe it was a remenaint from the previous patcher.
Removing it has solved this issue.

**Comment by PhantomGamers** [comment]
It might have been from old glory or something, I don't believe this is from any of my software. Though I'm going to reopen this because it shouldn't crash so I'll fix it in the next release

**Comment by GentlePuppet** [comment]
The only other patcher I had used was https://github.com/PhantomGamers/SteamFriendsPatcher
Before that existed I was manually adding the @import to the library css with my own custom css file.

**Comment by PhantomGamers** [comment]
I don't believe that patcher ever created .old files either so I'm not sure where that came from then 😅
