### ISSUE TITLE
recent steam update broke SFP

### ISSUE THREAD

**Issue by Velken** [PhantomGamers/SFP#56]
screenshots:
![image](https://user-images.githubusercontent.com/8467292/206841406-66fbaeac-f548-4ca6-8709-9890dd46cc12.png)

![image](https://user-images.githubusercontent.com/8467292/206841431-c0544965-71ed-4963-a954-957312cb678b.png)

**Comment by PhantomGamers** [comment]
It's still working fine for me, perhaps it is the skin you are using that is broken?

**Comment by Velken** [comment]
I am using ogSteam skin, but when I turn off SFP (not ogSteam skin) the broken stuff goes away

**Comment by PhantomGamers** [comment]
Well yeah, your library and friends list skins won't be applied without SFP.

**Comment by PhantomGamers** [comment]
If you go to SFP and click Open File -> Open friends.custom.css and clear all contents from that file and save it and restart Steam the friends list should load normally. If it does not then this indicates that it is a problem with SFP.
