### ISSUE TITLE
Linux - Launches to blank window

### ISSUE THREAD

**Issue by jvyden** [PhantomGamers/SFP#57]
![image](https://user-images.githubusercontent.com/40577357/209744986-f6dd0d51-df7c-457a-8ac6-6d49d05c56ab.png)

[SFP.log](https://github.com/PhantomGamers/SFP/files/10311590/SFP.log)

**Comment by PhantomGamers** [comment]
What linux distro are you running?

**Comment by jvyden** [comment]
This is Arch Linux, on Wayland with KDE. Nothing too special.

**Comment by PhantomGamers** [comment]
It's possible that either Avalonia or FluentAvalonia do not support Wayland. I've only tested it on Ubuntu running on WSL with X server, though I've seen it working for people running Linux natively I'm unsure if it has been tested with Wayland.

**Comment by jvyden** [comment]
Hmm, maybe, but I don't think that's related. I can tell from the icon that this is running under Xwayland (a compatibility layer for X11 apps to run under Wayland) and even tried changing the "XDG_SESSION_TYPE" variable to X11 to make sure it can only tell its under X11 and nothing changed.

I can try under X11 directly, though.

**Comment by jvyden** [comment]
Nope, that was it. I see the UI now.

I think this is an upstream bug either way so I'll try reporting this to Avalonia in the near future instead.
