### ISSUE TITLE
Bug/Glitch on Download page while downloading game

### ISSUE THREAD

**Issue by SleepDaemon** [PhantomGamers/SFP#6]
This is what it looks like when you downloading a game, but the game image blocks the download stats.

![image](https://user-images.githubusercontent.com/88533953/168521322-49e4e592-df83-416b-ba84-346d6b2f8763.png)

![image](https://user-images.githubusercontent.com/88533953/168521429-4f10514d-d82e-49fd-bb08-10f6aa96aa1d.png)

This could be just an issue with my skin, I'm using [Updated Metro Skin](https://github.com/redsigma/UPMetroSkin), but I am unsure.

**Comment by PhantomGamers** [comment]
Yeah I can confirm this behavior. This is an issue with the library skin though and not with SFP, the Metro skin, or the unofficial patch for Metro.

The library skin repo can be found here: https://github.com/AikoMidori/steam-library

**Comment by SleepDaemon** [comment]
> Yeah I can confirm this behavior. This is an issue with the library skin though and not with SFP, the Metro skin, or the unofficial patch for Metro.
> 
> The library skin repo can be found here: https://github.com/AikoMidori/steam-library

Hi, I downloaded the library skin repo but it still shows that issue.

**Comment by PhantomGamers** [comment]
Yes, it is an issue with the skin.

**Comment by SleepDaemon** [comment]
> Yes, it is an issue with the skin.

Okay then, ill submit this to Updated metro skin. Thanks for the help.

**Comment by PhantomGamers** [comment]
It is an issue with the library skin which controls the download page.

**Comment by SleepDaemon** [comment]
Aight, submitted to the https://github.com/AikoMidori/steam-library. Again thanks for your help, I wanted to share my custom metro skin with some friends so made this repo https://github.com/SleepDaemon/SteamDarkMode. Of course I gave credit cause I didn't make them I just manage the repo.
