### ISSUE TITLE
Title/Menu bars disappear when in Library view

### ISSUE THREAD

**Issue by pozzeur** [PhantomGamers/SFP#61]
The menu and title bars are disappearing now when in Library view. It makes navigating to other areas, like Store and Community only possible through the system tray context menu. Don't know exactly which Steam update version this began with but it was some time in January.

![Untitled](https://user-images.githubusercontent.com/124710027/217310551-aab0251b-61ad-4684-bd12-151da5dd9cb2.png)

**Comment by PhantomGamers** [comment]
This is a bug with your client skin and has nothing to do with SFP. I would recommend deleting your Steam/skins folder to resolve the issue.
