### ISSUE TITLE
Application appears to be compiled in debug mode

### ISSUE THREAD

**Issue by AcinonXDev** [PhantomGamers/SFP#64]
There are debugging information files (*.pdb) in the program's Windows version's directory. This is usually evidence of building applications with debugging enabled, which is not recommended for production/release builds.
This isn't critical, but I just thought I'd let you know.

**Comment by PhantomGamers** [comment]
The application is built in release mode. It is built using the powershell script in the root of the repo as seen here https://github.com/PhantomGamers/SFP/blob/main/createpublishedzip.ps1

The presence of the pdb file has nothing to do with whether the application was built in debug mode or not, this file simply allows errors to provide more information such as line  numbers, which makes development easier on my end.
