### ISSUE TITLE
Will this get me VAC banned?

### ISSUE THREAD

**Issue by VertofChest** [PhantomGamers/SFP#67]
My friend told me that modifying the Steam client could result in a vac ban or not being able to play on Secure servers...

**Comment by PhantomGamers** [comment]
This does not modify anything that should trigger VAC.

At least this is true as of right now, I suppose it's always possible that Valve could change what VAC detects and wind up banning for this, it's not a possibility that I'm personally concerned about but of course I can't guarantee that it won't happen.
