### ISSUE TITLE
Add  feature to inject JavaScript code to steam ui

### ISSUE THREAD

**Issue by CoelacanthusHex** [PhantomGamers/SFP#84]
Since steam 2023-04-27 beta version, SFP use CEF devtools to inject code. This way also supports JS besides CSS.
Steam has many elements with id like `somethingFixed_someHash`, JS code inject is suitable for this situation but pure CSS is difficult to match this thing. Even if it is successfully matched, once the hash changes, the user needs to manually find and fix it again. JS, on the other hand, can provide more flexible matching and modification capabilities.

https://github.com/ShadowMonster99/millennium-steam-patcher has supported this feature, and some theme like https://github.com/AikoMidori/SteamSkins has used it.

**Comment by PhantomGamers** [comment]
> Steam has many elements with id like somethingFixed_someHash, JS code inject is suitable for this situation but pure CSS is difficult to match this thing. Even if it is successfully matched, once the hash changes, the user needs to manually find and fix it again

JS should not be used for this purpose. Instead, use attribute value selectors like so: https://github.com/AikoMidori/steam-library/pull/23

![image](https://user-images.githubusercontent.com/844685/236003327-265edbff-5eb5-49b2-8ef9-2d401998a7fe.png)

As mentioned in the README.md of this repo, js support is coming but I suggest not using js when it is unnecessary as js injection will be disabled by default and users will be warned when enabling it as it can potentially result in users downloading malicious code onto their system.

**Comment by CoelacanthusHex** [comment]
Ok, I close it.

**Comment by PhantomGamers** [comment]
JS support has been added in 0.0.30-alpha, with [0.0.31-alpha](https://github.com/PhantomGamers/SFP/releases/tag/0.0.31-alpha) fixing js support for webkit.js
